# Generated by Django 5.0.7 on 2024-07-31 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='commetlike',
            name='unique_like_for_commet',
        ),
        migrations.AddConstraint(
            model_name='commetlike',
            constraint=models.UniqueConstraint(fields=('author', 'commet'), name='unique_like_for_commet'),
        ),
    ]
